/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pcv_algo_LinePickerNative */

#ifndef _Included_pcv_algo_LinePickerNative
#define _Included_pcv_algo_LinePickerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pcv_algo_LinePickerNative
 * Method:    init
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_pcv_algo_LinePickerNative_init
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     pcv_algo_LinePickerNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pcv_algo_LinePickerNative_release
  (JNIEnv *, jclass);

/*
 * Class:     pcv_algo_LinePickerNative
 * Method:    pick
 * Signature: (IIF)[I
 */
JNIEXPORT jintArray JNICALL Java_pcv_algo_LinePickerNative_pick
  (JNIEnv *, jclass, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
